check the use of JSON in secrets

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,6 +25,7 @@ jobs:
 
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
+        env:
+          JSON: ${{ secrets.SOME_JSON }}
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          echo ${JSON} | grep "foo" || echo "Not found"
